FROM python:3.6

WORKDIR /app

COPY jira_logger.py utils.py WeightedTask.py ./requirements.txt /app/
RUN pip install -U pip
RUN pip install -Ur requirements.txt

ENV JIRA_URL=<dev_jira_url>
RUN echo $JIRA_URL

ENTRYPOINT ["python3", "/app/jira_logger.py"]
CMD ["--help"]
